version: '3'
services:
  storageserver:
    container_name: ${APP_NAME}
    restart: always
    build:
      context: ./Dockerized
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_FPM_PORT:-9000}:9000
      - ${APP_PORT:-80}:80
      - ${APP_SSL_PORT:-443}:443
    volumes:
      - .:/var/www/html
      - ./Dockerized/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./Dockerized/php.ini:/etc/php/8.0/fpm/conf.d/docker-php-custom.ini
